import java.text.SimpleDateFormat

import com.github.spotbugs.snom.Effort

import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.PropertiesConfiguration
import org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder
import org.apache.commons.configuration2.builder.fluent.Parameters

buildscript {
    repositories {
        mavenCentral()
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'org.apache.commons:commons-configuration2:2.12.0'
        classpath 'commons-beanutils:commons-beanutils:1.10.1'
        classpath 'com.guardsquare:proguard-gradle:7.7.0'
        classpath 'com.github.spotbugs.snom:spotbugs-gradle-plugin:6.1.11'
        classpath 'org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:6.1.0.5360'
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'checkstyle'
    apply plugin: 'pmd'
    apply plugin: 'idea'
    apply plugin: 'com.github.spotbugs'
    apply plugin: 'jacoco'
    apply plugin: 'org.sonarqube'

    tasks.withType(JavaCompile) {
        options.release = 9
    }

    ext {
        privkeyid = '99'
        privkeyfile = "$rootDir/config/priv_key"
        pubkeyfile = "$rootDir/config/pub_key"
        mxtfile = project.layout.buildDirectory.dir("${rootProject.name}-v${getConfigValueForKey("module_build")}.mxt")
        outjar = project.layout.buildDirectory.dir("proguard-${rootProject.name}-v${getConfigValueForKey("module_build")}.jar")
    }

    repositories {
        mavenCentral()
        flatDir dirs: "$rootDir/lib"
    }

    spotbugs {
        effort = Effort.valueOf('MAX')
        excludeFilter = file("$rootDir/config/spotbugs-exclude.xml")
    }

    spotbugsMain {
        reports {
            html {
                required = true
            }
        }
    }

    jacoco {
        toolVersion = "0.8.13"
    }

    tasks.withType(Checkstyle) {
        reports {
            xml.required = false
            html.required = true
            html.stylesheet = resources.text.fromFile("$rootDir/config/checkstyle/checkstyle-noframes-sorted.xsl")
        }
    }

    checkstyle {
        toolVersion = "10.23.0"
    }

    pmd {
        toolVersion = "7.4.0"
        sourceSets = [sourceSets.main]
        ruleSets = []
        ruleSetFiles = files("$rootDir/config/pmd-ruleSet.xml")
    }

    sonar {
        properties {
            property "sonar.host.url", "https://sonarcloud.io"
            property "sonar.organization", "my-flow"
        }
    }
}

task createLibs(type: Exec) {
    description = 'Generates patched libraries from trusted source'
    executable "sh"
    args "-c", "scripts/create_libs.sh"
}

String getCurrentTimestamp() {
    Date today = new Date()
    SimpleDateFormat df = new SimpleDateFormat('yyyy-MM-dd HH:mm:ss')
    return df.format(today)
}

String getConfigValueForKey(String key) {
    File configFile = file("${project(':core').projectDir}/src/main/resources/com/moneydance/modules/features/paypalimporter/meta_info.dict")
    Parameters params = new Parameters()
    FileBasedConfigurationBuilder<PropertiesConfiguration> builder = 
        new FileBasedConfigurationBuilder<PropertiesConfiguration>(PropertiesConfiguration.class)
            .configure(params.properties().setFile(configFile))
    Configuration config = builder.getConfiguration()
    return config.getString("\"" + key + "\"").replaceAll("^\"|\"\$", "")
}
