name: Dependabot auto-approve and auto-merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ github.token }}
          skip-commit-verification: true

      - name: Wait for all checks to complete
        uses: lewagon/wait-on-check-action@v1.8.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ github.token }}
          wait-interval: 10
          running-workflow-name: dependabot
          allowed-conclusions: success

      - name: Approve PR if not already approved
        run: |
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ]; then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved, skipping to avoid notification spam"
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
