name: Build Gradle project

on:
  push:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: gradle/actions/wrapper-validation@v3
    - uses: gradle/actions/setup-gradle@v3
    - run: ./gradlew clean check test assemble
    - run: ./gradlew :core:sonar -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
