name: Build Gradle project

on:
  push:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v6
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: gradle/actions/wrapper-validation@v6.3.0
    - uses: gradle/actions/setup-gradle@v6.3.0
    - run: ./gradlew clean check test assemble
    - run: ./gradlew :core:sonar -Dsonar.token="${{ secrets.SONAR_TOKEN }}"
